#![cfg(unix)]

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

use anyhow::{Context, Result};
use cli_wrapper::cli::opencode::OpenCodeCli;
use cli_wrapper::cli::CliMetadata;
use cli_wrapper::tester::TestCase;
use cli_wrapper::{CliCommand, CliInterface, CliRegistry, CliStatus, CliTester, CliType, TestSuite};
use tempfile::TempDir;

fn env_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

use protocol::test_utils::EnvVarGuard;

struct MockCliSandbox {
    _root: TempDir,
    bin_dir: PathBuf,
    workspace_dir: PathBuf,
}

impl MockCliSandbox {
    fn new() -> Result<Self> {
        let root = tempfile::tempdir().context("failed to create mock CLI sandbox")?;
        let bin_dir = root.path().join("bin");
        let workspace_dir = root.path().join("workspace");
        fs::create_dir_all(&bin_dir).context("failed to create mock bin dir")?;
        fs::create_dir_all(&workspace_dir).context("failed to create mock workspace dir")?;

        for cli_name in ["claude", "codex", "gemini", "opencode"] {
            write_mock_cli(&bin_dir, cli_name)?;
        }

        Ok(Self { _root: root, bin_dir, workspace_dir })
    }

    fn bin_dir(&self) -> &Path {
        self.bin_dir.as_path()
    }

    fn workspace_dir(&self) -> &Path {
        self.workspace_dir.as_path()
    }
}

fn write_mock_cli(bin_dir: &Path, cli_name: &str) -> Result<()> {
    let script_path = bin_dir.join(cli_name);
    let script = format!(
        r#"#!/bin/sh
set -eu

if [ "${{1:-}}" = "--version" ]; then
  echo "{cli_name} 1.0.0"
  exit 0
fi

if [ -n "${{MOCK_CLI_ARG_LOG:-}}" ]; then
  printf '%s\n' "$*" >> "${{MOCK_CLI_ARG_LOG}}"
fi

args="$*"

case "$args" in
  *output.txt*)
    printf '%s\n' "generated by {cli_name}" > output.txt
    ;;
esac

case "$args" in
  *roadmap*)
    echo '{{"type":"assistant","content":"roadmap plan ready"}}'
    ;;
  *implement*)
    echo '{{"type":"assistant","content":"def add(a, b): return a + b"}}'
    ;;
  *review*)
    echo '{{"type":"assistant","content":"summary: review complete"}}'
    ;;
  *)
    echo '{{"type":"assistant","content":"ok"}}'
    ;;
esac
"#
    );

    fs::write(&script_path, script)
        .with_context(|| format!("failed to write mock executable for {} at {}", cli_name, script_path.display()))?;

    let mut perms = fs::metadata(&script_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&script_path, perms)
        .with_context(|| format!("failed to set executable permissions on {}", script_path.display()))?;

    Ok(())
}

#[tokio::test]
async fn e2e_registry_discovers_mock_clis_and_health_is_available() -> Result<()> {
    let _lock = env_lock().lock().expect("env lock should not be poisoned");
    let sandbox = MockCliSandbox::new()?;
    let path_value = sandbox.bin_dir().to_string_lossy().to_string();
    let _path_guard = EnvVarGuard::set("PATH", Some(&path_value));

    let mut registry = CliRegistry::new();
    let discovered = registry.discover_clis().await?;
    assert_eq!(discovered, 4, "expected mock discovery for claude/codex/gemini/opencode");

    let statuses = registry.check_all_status().await;
    for cli_type in [CliType::Claude, CliType::Codex, CliType::Gemini, CliType::OpenCode] {
        assert_eq!(
            statuses.get(&cli_type),
            Some(&CliStatus::Available),
            "{cli_type:?} should be healthy in the mock registry"
        );
    }

    Ok(())
}

#[tokio::test]
async fn e2e_opencode_model_matrix_supports_glm_and_minimax() -> Result<()> {
    let _lock = env_lock().lock().expect("env lock should not be poisoned");
    let sandbox = MockCliSandbox::new()?;
    let cli = OpenCodeCli::new(CliMetadata::new(CliType::OpenCode, sandbox.bin_dir().join("opencode")));

    for (model, label) in [("zai-coding-plan/glm-4.7", "glm"), ("minimax/MiniMax-M2.1", "minimax")] {
        let args_log_path = sandbox.workspace_dir().join(format!("{label}.args.log"));

        let command = CliCommand::new("implement function add two numbers")
            .with_working_dir(sandbox.workspace_dir().to_path_buf())
            .with_env("OPENCODE_MODEL".to_string(), model.to_string())
            .with_env("MOCK_CLI_ARG_LOG".to_string(), args_log_path.to_string_lossy().to_string());
        let output = cli.execute(&command).await?;
        assert!(output.is_success(), "model {model} should execute");
        assert!(
            output.stdout.contains("\"type\":\"assistant\""),
            "model {model} should emit structured JSON-like output"
        );

        let logged_args = fs::read_to_string(&args_log_path)
            .with_context(|| format!("expected CLI args log at {}", args_log_path.display()))?;
        assert!(
            logged_args.contains("-m"),
            "OpenCode invocation should include -m for model {model}; args={logged_args}"
        );
        assert!(logged_args.contains(model), "OpenCode invocation should include model {model}; args={logged_args}");
    }

    Ok(())
}

#[tokio::test]
async fn e2e_coding_agent_task_suite_passes_for_opencode() -> Result<()> {
    let _lock = env_lock().lock().expect("env lock should not be poisoned");
    let sandbox = MockCliSandbox::new()?;
    let path_value = sandbox.bin_dir().to_string_lossy().to_string();
    let _path_guard = EnvVarGuard::set("PATH", Some(&path_value));
    let _default_model_guard = EnvVarGuard::set("OPENCODE_MODEL", Some("zai-coding-plan/glm-4.7"));

    let mut registry = CliRegistry::new();
    registry.discover_clis().await?;
    let opencode = registry.get(CliType::OpenCode).context("expected opencode in discovered registry")?;

    let expected_output_file = sandbox.workspace_dir().join("output.txt");
    let suite = TestSuite::new("Coding Agent E2E")
        .with_description("Planning, implementation, review, and file output checks")
        .add_test(
            TestCase::new("planning_task", "build roadmap for workflow hardening")
                .expect_output("roadmap plan ready")
                .with_timeout(10),
        )
        .add_test(
            TestCase::new("implementation_task", "implement function add two numbers")
                .expect_output("def add")
                .with_timeout(10),
        )
        .add_test(
            TestCase::new("review_task", "review patch and summarize risks").expect_output("summary").with_timeout(10),
        )
        .add_test(
            TestCase::new("artifact_task", "write output.txt with fixture content")
                .expect_output("ok")
                .expect_file(expected_output_file.clone())
                .with_timeout(10),
        );

    let tester = CliTester::new().with_temp_dir(sandbox.workspace_dir().to_path_buf());
    let results = tester.test_cli(opencode, &suite).await?;
    assert_eq!(results.len(), 4, "suite should execute all task scenarios");

    let failures: Vec<String> = results
        .iter()
        .filter(|result| !result.passed)
        .map(|result| format!("{}: failures={:?} error={:?}", result.test_name, result.failures, result.error))
        .collect();
    assert!(failures.is_empty(), "expected coding-agent suite to pass, failures: {failures:?}");

    assert!(expected_output_file.exists(), "artifact_task should create {}", expected_output_file.display());
    let json_like_outputs = results.iter().filter(|result| result.output.trim().starts_with('{')).count();
    assert!(json_like_outputs >= 3, "expected most suite outputs to be machine-parseable JSON-like lines");

    Ok(())
}
